#!/bin/sh
set -eu

: "${REDIS_PASSWORD:?REDIS_PASSWORD is required}"

# Defaults (override via .env)
REDIS_PORT="${REDIS_PORT:-6379}"
MAXMEMORY="${REDIS_MAXMEMORY:-200mb}"                 # keep below mem_limit to avoid OOM
POLICY="${REDIS_MAXMEMORY_POLICY:-allkeys-lru}"

# Persistence mode:
# - AOF only (recommended): REDIS_SAVE="" and REDIS_APPENDONLY=yes
APPENDONLY="${REDIS_APPENDONLY:-yes}"
APPENDFSYNC="${REDIS_APPENDFSYNC:-everysec}"
SAVE="${REDIS_SAVE:-""}"                             # empty disables RDB snapshots

# Where Redis stores data (volume)
DATA_DIR="${REDIS_DATA_DIR:-/data}"

CONF_DIR="/etc/redis"
CONF_FILE="$CONF_DIR/redis.generated.conf"

mkdir -p "$CONF_DIR"

cat > "$CONF_FILE" <<EOF
# Generated by run-redis.sh

bind 0.0.0.0
port $REDIS_PORT
protected-mode yes

# Security
requirepass $REDIS_PASSWORD

# Run in foreground (Docker)
daemonize no
supervised no
logfile ""

# Networking
tcp-keepalive 300
timeout 0

# Persistence
appendonly $APPENDONLY
appendfsync $APPENDFSYNC
aof-use-rdb-preamble yes
save $SAVE

# Memory
maxmemory $MAXMEMORY
maxmemory-policy $POLICY

# Data dir
dir $DATA_DIR
EOF

echo "Starting Redis on port=$REDIS_PORT maxmemory=$MAXMEMORY policy=$POLICY appendonly=$APPENDONLY save='$SAVE'"

exec redis-server "$CONF_FILE"
